### ISSUE TITLE
undefined method `merge' for false:FalseClass (NoMethodError)

### ISSUE THREAD

**Issue by halbtuerke** [brandonpittman/nikki#3]
Hi,

I just installed nikki and every time I try to add a new entry I get the following error message:

```
/Users/patrick/.gem/ruby/2.2.1/gems/nikki-0.5.3/lib/nikki.rb:44:in `new': undefined method `merge' for false:FalseClass (NoMethodError)
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /Users/patrick/.gem/ruby/2.2.1/gems/nikki-0.5.3/bin/nikki:5:in `<top (required)>'
from /Users/patrick/.gem/ruby/2.2.1/bin/nikki:23:in `load'
from /Users/patrick/.gem/ruby/2.2.1/bin/nikki:23:in `<main>'
```

**Comment by brandonpittman** [comment]
I just pushed a new version. See if that helps.

**Comment by halbtuerke** [comment]
Unfortunately it still does not work. After having to install the `stickynotifications` gem by hand (it was missing somehow) I get the following error:

```
/Users/patrick/.gem/ruby/2.2.1/gems/nikki-0.5.4/lib/nikki.rb:48:in `new': undefined method `merge' for false:FalseClass (NoMethodError)
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /Users/patrick/.gem/ruby/2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /Users/patrick/.gem/ruby/2.2.1/gems/nikki-0.5.4/bin/nikki:5:in `<top (required)>'
from /Users/patrick/.gem/ruby/2.2.1/bin/nikki:23:in `load'
from /Users/patrick/.gem/ruby/2.2.1/bin/nikki:23:in `<main>'
```

**Comment by brandonpittman** [comment]
It's merging with your existing journal file, so I imagine there might be some problem with the existing journal file.

**Comment by brandonpittman** [comment]
Did you run `nikki setup` to start with?

**Comment by halbtuerke** [comment]
Yes, I have run `nikki setup`.

The source of the error seems to be the empty `nikki.yaml` file. This leads to the call of `YAML.load` to return the `FalseClass`, which does not respond to the `merge` call.

I have manually put an entry into the file and now `nikki new` seems to work.

Should `new` also work with an empty file?

**Comment by brandonpittman** [comment]
I never set it up to do so. Nikki was one of the first projects I ever built and my design wasn't so hot. :(
